Fix BitSet implementation to use bool instead of int
cgarwood/python-openzwave-mqtt pull request #95
Opened 2020-10-02 17:58 UTC by raman325

Per the [docs](https://github.com/OpenZWave/qt-openzwave/blob/master/docs/MQTT.md#setvalue) the value of a bit is supposed to be `true` or `false`. I also updated the structure of the input value (list of dicts instead of dict of bits) because I wasn't setting the new value correctly and this requires less transformation during this step.

2020-10-02 17:59 UTC, raman325 commented
@kpine does this make more sense now?

2020-10-02 18:07 UTC, raman325 commented
Assuming this gets merged, can we also do a patch release?

2020-10-03 00:35 UTC, MartinHjelmare reviewed
Please add some unit tests where we test different input to these functions.

2020-10-03 02:38 UTC, raman325 commented
Good idea

2020-10-03 08:02 UTC, MartinHjelmare requested changes

2020-10-03 08:02 UTC, MartinHjelmare commented on test/util/test_node.py
> +    _set_bool_config_parameter(mock_value, True)
Call `set_config_parameter` and assert the return value.

2020-10-03 16:33 UTC, MartinHjelmare commented on test/util/test_node.py
> +    with patch("openzwavemqtt.util.node.OZWNode.get_value", return_value=mock_value):
I'd extract the common mocks, patches and fixtures to pytest fixtures.

```py
@pytest.fixture(name="node")
def mock_node_fixture(options):
    """Mock OZWValue."""
    return OZWNode(options, None, "test", None)

@pytest.fixture(name="mock_value")
def mock_value_fixture():
    """Mock OZWValue."""
    return Mock(spec=OZWValue)

@pytest.fixture(name="mock_get_value")
def mock_get_value_fixture(mock_value):
    """Patch get_value."""
    with patch("openzwavemqtt.util.node.OZWNode.get_value", return_value=mock_value):
        yield

def test_set_bool_config_parameter(node, mock_value, mock_get_value):
    """Test setting a ValueType.BOOL config parameter."""
    mock_value.type = ValueType.BOOL

    assert set_config_parameter(node, 1, True)
    assert not set_config_parameter(node, 1, False)
    assert set_config_parameter(node, 1, "True")
    assert not set_config_parameter(node, 1, "False")

    with pytest.raises(WrongTypeError):
        set_config_parameter(node, 1, "test")

    with pytest.raises(WrongTypeError):
        set_config_parameter(node, 1, 95)
```

2020-10-03 17:10 UTC, MartinHjelmare approved these changes
Looks good!

2020-10-03 17:10 UTC, merged